import {
  LayoutDashboard,
  CreditCard,
  PieChart,
  Bot,
  LogOut,
  Settings,
  WalletCards,
  Target,
  Wallet,
  Banknote,
  ShoppingCart,
  TrendingUp,
  ArrowRight,
  ChartNoAxesCombined,
  ShieldCheck,
} from 'lucide-react'

export const ICONS = {
  dashboard: LayoutDashboard,
  transaction: CreditCard,
  budgets: WalletCards,
  goal: Target,
  analytics: PieChart,
  ai: Bot,
  logout: LogOut,
  settings: Settings,
  wallet: Wallet,
  banknote: Banknote,
  shoppingCart: ShoppingCart,
  trendingUp: TrendingUp,
  arrowRight: ArrowRight,
  chartNoAxesCombined: ChartNoAxesCombined,
  shieldCheck: ShieldCheck,
}
